from colorama import Fore, Back, Style
print(Back.CYAN +'                                                     ')
print(Back.CYAN +'                                                     ')
print(Back.CYAN +'                                                     ')
print(Back.CYAN +'                         ',Back.RED +' ',Back.CYAN +'                         ')
print(Back.CYAN +'                        ',Back.RED +'   ',Back.CYAN +'                        ')
print(Back.CYAN +'                       ',Back.RED +'     ',Back.CYAN +'                       ')
print(Back.CYAN +'                      ',Back.RED +'       ',Back.CYAN +'                      ')
print(Back.CYAN +'                     ',Back.RED +'         ',Back.CYAN +'                     ')
print(Back.CYAN +'                    ',Back.RED +'           ',Back.CYAN +'                    ')
print(Back.CYAN +'                   ',Back.RED +'             ',Back.CYAN +'                   ')
print(Back.CYAN +'                  ',Back.RED +'               ',Back.CYAN +'                  ')
print(Back.CYAN +'                 ',Back.RED +'                 ',Back.CYAN +'                 ')
print(Back.CYAN +'                ',Back.RED +'                   ',Back.CYAN +'                ')
print(Back.CYAN +'              ',Back.RED +'                       ',Back.CYAN +'              ')
print(Back.CYAN +'            ',Back.RED +'                           ',Back.CYAN +'            ')
print(Back.CYAN +'              ',Back.WHITE +'                       ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'                       ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'                       ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'             ',Back.YELLOW +'    ',Back.WHITE +'    ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'             ',Back.YELLOW +'    ',Back.WHITE +'    ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'                       ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'                       ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'       ',Back.MAGENTA +'    ',Back.WHITE +'',Back.WHITE +'         ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'       ',Back.MAGENTA +'    ',Back.WHITE +'',Back.WHITE +'         ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'       ',Back.MAGENTA +'    ',Back.WHITE +'',Back.WHITE +'         ',Back.CYAN +'              ')
print(Back.CYAN +'              ',Back.WHITE +'       ',Back.MAGENTA +'    ',Back.WHITE +'',Back.WHITE +'         ',Back.CYAN +'              ')
print(Back.CYAN +'            ',Back.GREEN +'                           ',Back.CYAN +'            ')